# wallust v3.4
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "labmixed"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16

# palette = "harddark16"
palette = "dark16"


# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = false 

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
# saturation = 100

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }
# ghostty.template = 'ghostty'
# ghostty.target = '~/.config/ghostty/themes/wal'

wezterm.template= 'wezterm.toml'
wezterm.target = '~/.config/wezterm/colors/wallust.toml'

vscode = { src = 'vscode.json', dst = '~/.cache/wallust/colors.json' }
vscode2 = { src = 'vscode', dst = '~/.cache/wallust/colors' }

themecord.template = "colors-discord.css"
themecord.target = '~/.cache/wallust/discord-colors.css'

waybar.template = 'waybar.css'
waybar.target = '~/.config/waybar/style.css'

pywalfox.template = 'pywalfox.json'
pywalfox.target = '~/.cache/wal/colors.json'

firefoxcss.template = 'firefox-colors.css'
firefoxcss.target = '~/.cache/wal/colors.css'

comfyspicetify.template = 'comfy-spicetify.ini'
comfyspicetify.target = '~/.config/spicetify/Themes/Comfy/color.ini'

rofi.template = 'wallust.rasi'
rofi.target = '/home/itmoth/.config/rofi/colors/wallust.rasi'

sioyek.template = 'sioyek.config'
sioyek.target = '/home/itmoth/.config/sioyek/prefs_user.config'

mako.template = 'mako-config'
mako.target = '~/.config/mako/config'