[colors]
# The default text color
foreground = "{{foreground}}"
# The default background color
background = "{{background}}"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "{{cursor}}"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "{{background}}"
# Specifies the border color of the cursor when the cursor style is set to Block,
# of the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "{{cursor}}"

# the foreground color of selected text
selection_fg = "{{foreground}}"
# the background color of selected text
selection_bg = "{{cursor}}"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "{{cursor}}"

# The color of the split lines between panes
split = "{{cursor}}"

ansi = ["{{color0}}", "{{color1}}", "{{color2}}", "{{color3}}", "{{color4}}", "{{color5}}", "{{color6}}", "{{color7}}"]
brights = ["{{color8}}", "{{color9}}", "{{color10}}", "{{color11}}", "{{color12}}", "{{color13}}", "{{color14}}", "{{color15}}"]

[colors.tab_bar]
background = '{{background}}'
inactive_tab_edge = '{{background}}'

[colors.tab_bar.active_tab]
bg_color = '{{color9}}'
fg_color = '{{background}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '{{color0}}'
fg_color = '{{color7}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '{{color0}}'
fg_color = '{{color7}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '{{color11}}'
fg_color = '{{foreground}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '{{color11}}'
fg_color = '{{foreground}}'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'